version: 2.1

orbs:
  pytest: thekevjames/pytest@0.0.60
  coverage-reporter: codacy/coverage-reporter@13.5.3

workflows:
    pytest:
      jobs:
        - pytest/pytest:
            python_version: '3.10.0' 
            install_args: pytest-cov
            args: -v --cov --cov-report=xml:coverage.xml
            post-steps:
              - coverage-reporter/send_report:
                  coverage-reports: coverage.xml
                  project-token: $CODACY_PROJECT_TOKEN

        

